name: Build Docker image

on:
  pull_request:
    branches: [ master ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
    - name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        repository: vasilvasilev97/docker-stats-monitor
        push: false
