name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@0.0.1
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.16.3
    - name: Run tests
      run: sbt test
